name: Impact-Scan Auto-Fix

on:
  schedule:
    # Run weekly on Monday at 2 AM
    - cron: '0 2 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-fix:
    name: Auto-Fix Security Vulnerabilities
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Impact-Scan
        run: |
          python -m pip install --upgrade pip
          pip install impact-scan
      
      - name: Run Scan with Auto-Fix
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          impact-scan scan . \
            --profile comprehensive \
            --ai groq \
            --fix-auto \
            --yes \
            --fix-strategy conservative \
            --output fixes.json
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "🔧 [Impact-Scan] Auto-fix security vulnerabilities"
          body: |
            ## 🛡️ Automated Security Fixes

            This PR was automatically generated by Impact-Scan with AI-powered fixes.

            ### 📊 Changes Summary
            - Fixed vulnerabilities with HIGH confidence
            - All fixes reviewed and validated by AI
            - Unified diff format for easy review

            ### ✅ Next Steps
            1. Review the proposed changes
            2. Run tests to verify functionality
            3. Merge if all checks pass

            ---
            Generated by [Impact-Scan](https://github.com/Ani07-05/impact-scan)
          branch: impact-scan/auto-fix-${{ github.run_number }}
          delete-branch: true
          labels: security,automated
          commit-message: "🔧 Auto-fix: Apply AI-generated security fixes"
